### ISSUE TITLE
Is there a way to set a robots.txt config?

### ISSUE THREAD

**Issue by jalemann** [matfantinel/sveltekit-static-blog-template#6]
I was wondering if there is a way to set a robots.txt file? Or would I have to add it manually after building?

**Comment by matfantinel** [comment]
@jalemann  I believe just adding the file to the /static folder is enough! Everything in there is gonna be publicly accessible, so if a search engine tries going to your-site.com/robots.txt it will find it.

**Comment by jalemann** [comment]
Thanks, that works!
